export interface Project {
  id: number;
  title: string;
  slug: string;
  description: string;
  image: string;
  link_demo: string | null;
  link_github: string | null;
  stacks: string[];
  content: string | null;
  is_featured: boolean;
}

const projectImage = (fileName: string) => encodeURI(`/project/${fileName}`);

export const projects: Project[] = [
  {
    id: 1,
    title: '86 Photo Studio Website',
    slug: '86-photo-studio-website',
    description: 'A polished studio website that showcases photography services, featured work, and a simple booking path for potential clients.',
    image: projectImage('86PhotoStudioWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    content: 'A polished studio website that showcases photography services, featured work, and a simple booking path for potential clients. The layout focuses on visual storytelling, clear service presentation, and a clean way to highlight the studio identity.',
    is_featured: true,
  },
  {
    id: 2,
    title: 'Apotek Lehan Farma Website',
    slug: 'apotek-lehan-farma-website',
    description: 'A pharmacy website that presents services, store information, and a trustworthy first impression for local customers.',
    image: projectImage('ApotekLehanFarmaWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'React', 'Tailwind CSS'],
    content: 'A pharmacy website that presents services, store information, and a trustworthy first impression for local customers. The structure is designed to make essential information easy to find and keep the experience straightforward on mobile devices.',
    is_featured: false,
  },
  {
    id: 3,
    title: 'Desa Sawotratap Website',
    slug: 'desa-sawotratap-website',
    description: 'An official village website built to share announcements, public information, and community updates in one place.',
    image: projectImage('DesaSawotratapWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    content: 'An official village website built to share announcements, public information, and community updates in one place. The content hierarchy keeps daily information, administrative details, and community news easy to scan.',
    is_featured: false,
  },
  {
    id: 4,
    title: 'Desa Watu Pari Website',
    slug: 'desa-watu-pari-website',
    description: 'A village information website designed to help residents and visitors access public content quickly and clearly.',
    image: projectImage('DesaWatuPariWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    content: 'A village information website designed to help residents and visitors access public content quickly and clearly. The page structure emphasizes clarity, local identity, and practical information for everyday use.',
    is_featured: false,
  },
  {
    id: 5,
    title: 'Elevra Digital Era Website',
    slug: 'elevra-digital-era-website',
    description: 'A digital agency website that introduces services, capabilities, and a modern brand presence.',
    image: projectImage('ElevraDigitalEraWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['React', 'Next.js', 'Tailwind CSS', 'Vercel'],
    content: 'A digital agency website that introduces services, capabilities, and a modern brand presence. It balances bold visuals with concise copy so visitors can quickly understand the offering and next steps.',
    is_featured: true,
  },
  {
    id: 6,
    title: 'Jatim Innovator Website',
    slug: 'jatim-innovator-website',
    description: 'A platform for innovation programs, updates, and community-driven initiatives across East Java.',
    image: projectImage('JatimInnovatorWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Vue.js', 'TypeScript', 'Tailwind CSS'],
    content: 'A platform for innovation programs, updates, and community-driven initiatives across East Java. The design supports long-form updates, highlight sections, and an approachable information flow.',
    is_featured: false,
  },
  {
    id: 7,
    title: 'Jeep Alamku Kintamani Website',
    slug: 'jeep-alamku-kintamani-website',
    description: 'A tour website for Jeep adventures in Kintamani with route highlights, trip details, and a stronger booking intent.',
    image: projectImage('JeepAlamkuKintamaniWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    content: 'A tour website for Jeep adventures in Kintamani with route highlights, trip details, and a stronger booking intent. The layout is meant to feel adventurous while still keeping the key trip information easy to compare.',
    is_featured: true,
  },
  {
    id: 8,
    title: 'Lhi Fun Run Website',
    slug: 'lhi-fun-run-website',
    description: 'An event website built to promote registration, event details, and the energetic feel of a fun run community.',
    image: projectImage('LhiFunRunWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['React', 'Tailwind CSS', 'Firebase'],
    content: 'An event website built to promote registration, event details, and the energetic feel of a fun run community. The content is arranged to help participants quickly understand the schedule, atmosphere, and call to action.',
    is_featured: false,
  },
  {
    id: 9,
    title: 'Portfolio Ammar Wicaksono',
    slug: 'portfolio-ammar-wicaksono',
    description: 'A personal portfolio that introduces background, selected work, and the easiest way to get in touch.',
    image: projectImage('PortfolioAmmarWicaksono.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    content: 'A personal portfolio that introduces background, selected work, and the easiest way to get in touch. It keeps the focus on identity, portfolio highlights, and a smooth first impression for prospective clients or employers.',
    is_featured: false,
  },
  {
    id: 10,
    title: 'Portfolio Iman AI Specialist & Graphic Designer',
    slug: 'portfolio-iman-ai-specialist-graphic-designer',
    description: 'A personal portfolio combining AI expertise and graphic design work into one clear showcase.',
    image: projectImage('PortfolioImanAISpecialist&GrapichDesigner.png'),
    link_demo: null,
    link_github: null,
    stacks: ['React', 'Python', 'Django', 'Tailwind CSS'],
    content: 'A personal portfolio combining AI expertise and graphic design work into one clear showcase. The presentation supports both technical credibility and visual creativity without making the page feel crowded.',
    is_featured: true,
  },
  {
    id: 11,
    title: 'Portfolio Iman ASN',
    slug: 'portfolio-iman-asn',
    description: 'A professional portfolio for an ASN profile, presenting identity, achievements, and career highlights.',
    image: projectImage('PortfolioImanASN.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    content: 'A professional portfolio for an ASN profile, presenting identity, achievements, and career highlights. The design prioritizes formality, readability, and a clean visual structure for professional review.',
    is_featured: false,
  },
  {
    id: 12,
    title: 'Posyandu Bayi Website',
    slug: 'posyandu-bayi-website',
    description: 'A family-friendly health information website focused on infant posyandu services and practical guidance.',
    image: projectImage('PosyanduBayiWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'MySQL'],
    content: 'A family-friendly health information website focused on infant posyandu services and practical guidance. The layout keeps important health information calm, readable, and easy for guardians to follow.',
    is_featured: false,
  },
  {
    id: 13,
    title: 'Telkom Wave Website',
    slug: 'telkom-wave-website',
    description: 'A branded website experience designed to communicate Telkom Wave updates, initiatives, and campaign details.',
    image: projectImage('TelkomWaveWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['React', 'GraphQL', 'Prisma', 'PostgreSQL'],
    content: 'A branded website experience designed to communicate Telkom Wave updates, initiatives, and campaign details. The page direction leans into a modern corporate feel with strong hierarchy and concise messaging.',
    is_featured: false,
  },
  {
    id: 14,
    title: 'Z Learn Website',
    slug: 'z-learn-website',
    description: 'An education platform concept for structured learning, accessible resources, and study content.',
    image: projectImage('ZLearnWebsite.png'),
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TypeScript', 'Firebase'],
    content: 'An education platform concept for structured learning, accessible resources, and study content. The interface is organized around progression, clarity, and a low-friction learning experience.',
    is_featured: false,
  },
];
